# config/_default/menus.en.toml

[[main]]
  name = "About"
  pageRef = "about.md"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects.md"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/mehmetalici"
  weight = 30
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/mehmet-alici/"
  weight = 30
  [main.params]
    icon = "linkedin"
    showName = false
    target = "_blank"

# [[footer]]
#   name = "Privacy"
#   pageRef = "privacy"
